version: '3.8'

volumes:
  vol-mariadb:

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      MYSQL_USER: userdb
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: testdb
    volumes:
      - vol-mariadb:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - '8082:80'
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: q1w2e3r4